== Deploy Microservices

=== Deploy customer

Make sure you are logged in

[source,bash]
----
oc whoami
----

and you have setup the project/namespace

[source,bash]
----
export TUTORIAL_USER=<xxx>
export TUTORIAL_PROJECT=<xxx>
oc new-project $TUTORIAL_PROJECT

oc login -u admin # You need to be cluster-admin
oc adm policy add-scc-to-user privileged -z default -n $TUTORIAL_PROJECT

oc login -u $TUTORIAL_USER # return normal user
----

Then clone the git repository

[source,bash]
----
git clone https://github.com/literalice/istio-tutorial
cd istio-tutorial
----

Start deploying the microservice projects, starting with customer

Make sure `istioctl` is in your `PATH`:

istioctl install:
https://github.com/istio/istio/releases

[source,bash]
----
$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
----

==== Customer build using OpenShift S2I strategy

[source, bash]
----
oc new-app --name=customer --context-dir=customer/java/springboot -e JAEGER_SERVICE_NAME=customer JAEGER_ENDPOINT=http://jaeger-collector.istio-system.svc:14268/api/traces JAEGER_PROPAGATION=b3 JAEGER_SAMPLER_TYPE=const JAEGER_SAMPLER_PARAM=1 JAVA_OPTIONS='-Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true' fabric8/s2i-java~https://github.com/redhat-developer-demos/istio-tutorial -o yaml  > customer.yml
oc apply -f <(istioctl kube-inject -f customer.yml) -n $TUTORIAL_PROJECT
oc delete svc/customer ; oc expose dc/customer --port=8080
oc logs bc/customer -f
----

==== Expose customer

Since the `customer` service is the one our users will interact with, let's add an OpenShift Route that exposes that endpoint.

[source,bash]
----
oc expose service customer

oc get route
oc get pods -w
----

IMPORTANT: If your pod fails with `ImagePullBackOff`, it's possible that your current terminal isn't using the proper Docker Environment. See link:#setup-environment[Setup environment].

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

Then test the customer endpoint

[source,bash]
----
oc get routes customer -o jsonpath --template '{.spec.host}'
curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
----

You should see the following error because the services `preference` and `recommendation` are not yet deployed.

----
customer => I/O error on GET request for "http://preference:8080": preference; nested exception is java.net.UnknownHostException: preference
----

Also review the logs

[source,bash]
----
oc logs dc/customer -c customer
----

You should see a stacktrace containing this cause:

[source,bash]
----
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://preference:8080": preference; nested exception is java.net.UnknownHostException: preference
----

=== Deploy preference

==== Preference build using OpenShift S2I strategy

[source, bash]
----
oc new-app -l app=preference,version=v1 --name=preference-v1 --context-dir=preference/java/springboot -e JAEGER_SERVICE_NAME=preference JAEGER_ENDPOINT=http://jaeger-collector.istio-system.svc:14268/api/traces JAEGER_PROPAGATION=b3 JAEGER_SAMPLER_TYPE=const JAEGER_SAMPLER_PARAM=1 JAVA_OPTIONS='-Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true' fabric8/s2i-java~https://github.com/redhat-developer-demos/istio-tutorial -o yaml  > preference.yml
oc apply -f <(istioctl kube-inject -f preference.yml) -n $TUTORIAL_PROJECT
oc delete svc/preference-v1 ; oc expose dc/preference-v1 --port=8080 --name=preference
oc logs bc/preference-v1 -f
----

==== Wait preference to be deployed

[source, bash]
----
oc get pods -w
----

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash]
----
curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
----

It will respond with an error since the service `recommendation` is not yet deployed.

NOTE: We could make this a bit more resilient in a future iteration of this tutorial

[source,bash]
----
customer => 503 preference => I/O error on GET request for "http://recommendation:8080": recommendation; nested exception is java.net.UnknownHostException: recommendation
----

and check out the logs

[source,bash]
----
oc logs dc/preference-v1 -c preference-v1
----

You should see a stacktrace containing this cause:

[source,bash]
----
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://recommendation:8080": recommendation; nested exception is java.net.UnknownHostException: recommendation
----

=== Deploy recommendation

IMPORTANT: The tag `v1` at the end of the image name matters. We will be creating a `v2` version of `recommendation` later in this tutorial. Having both a `v1` and `v2` version of the `recommendation` code will allow us to exercise some interesting aspects of Istio's capabilities.

==== Recommendation build using OpenShift S2I strategy

[source, bash]
----
oc new-app -l app=recommendation,version=v1 --name=recommendation-v1 --context-dir=recommendation/java/vertx JAVA_OPTIONS='-Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true' fabric8/s2i-java~https://github.com/redhat-developer-demos/istio-tutorial -o yaml  > recommendation.yml
oc apply -f <(istioctl kube-inject -f recommendation.yml) -n $TUTORIAL_PROJECT
oc delete svc/recommendation-v1 ; oc create -f recommendation/kubernetes/Service.yml
oc logs bc/recommendation-v1 -f
----

==== Wait recommendation to be deployed

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash]
----
curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
----

it should now return

[source,bash]
----
customer => preference => recommendation v1 from '99634814-sf4cl': 1
----

and you can monitor the `recommendation` logs with

[source,bash]
----
oc logs dc/preference-v1 -c preference-v1
----
