== Advanced Route Rules

=== Smart routing based on user-agent header (Canary Deployment)

What is your user-agent?

https://www.whoishostingthis.com/tools/user-agent/[https://www.whoishostingthis.com/tools/user-agent/]

Note: the "user-agent" header is added to OpenTracing baggage in the Customer service. From
there it is automatically propagated to all downstream services. To enable automatic
baggage propagation all intermediate services have to be instrumented with OpenTracing.
The baggage header for user agent has following form `baggage-user-agent: <value>`.

==== Set recommendation to all v1

[source,bash]
----
oc login -u admin

istioctl create -f istiofiles/destination-rule-recommendation-v1-v2.yml -n $TUTORIAL_PROJECT
istioctl create -f istiofiles/virtual-service-recommendation-v1.yml -n $TUTORIAL_PROJECT
----

==== Set Safari users to v2

[source,bash]
----
istioctl replace -f istiofiles/virtual-service-safari-recommendation-v2.yml -n $TUTORIAL_PROJECT

istioctl get virtualservice -n $TUTORIAL_PROJECT
----

and test with a Safari (or even Chrome on Mac since it includes Safari in the string). Safari only sees v2 responses from recommendation

and test with a Firefox browser, it should only see v1 responses from recommendation.

There are two ways to get the URL for your browser:

[source,bash]
----
open "http://`oc get routes customer -o jsonpath --template '{.spec.host}'`"
----

That will open the openshift service `customer` in browser

Or

if you need just the url alone:

[source,bash]
----
oc get routes customer -o jsonpath --template '{.spec.host}'
----

You can also attempt to use the curl -A command to test with different user-agent strings. 

[source,bash]
----
curl -A Safari `oc get routes customer -o jsonpath --template '{.spec.host}'`
curl -A Firefox `oc get routes customer -o jsonpath --template '{.spec.host}'`
----

You can describe the virtualservice to see its configuration

[source,bash]
----
istioctl get virtualservice -o yaml -n $TUTORIAL_PROJECT
----

===== Remove the Safari rule

[source,bash]
----
istioctl delete -f istiofiles/virtual-service-safari-recommendation-v2.yml -n $TUTORIAL_PROJECT
----

==== Set mobile users to v2

[source,bash]
----
istioctl create -f istiofiles/virtual-service-mobile-recommendation-v2.yml -n $TUTORIAL_PROJECT

curl -A "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4(KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5" `oc get routes customer -o jsonpath --template '{.spec.host}'`
----

===== Clean up

[source,bash]
----
istioctl delete -f istiofiles/destination-rule-recommendation-v1-v2.yml -n $TUTORIAL_PROJECT
istioctl delete -f istiofiles/virtual-service-mobile-recommendation-v2.yml -n $TUTORIAL_PROJECT
----

=== Mirroring Traffic (Dark Launch)

[source,bash]
----
oc get pods -l app=recommendation -n $TUTORIAL_PROJECT
----

You should have 2 pods for recommendation based on the steps above

[source,bash]
----
istioctl get virtualservice -n $TUTORIAL_PROJECT
istioctl get destinationrule
----

You should have NO virtualservice nor destinationrule (in `tutorial` namespace) `istioctl get virtualservice` `istioctl get destinationrule` 
if so `istioctl delete virtualservice virtualservicename -n $TUTORIAL_PROJECT` and `istioctl delete destinationrule destinationrulename -n $TUTORIAL_PROJECT`

Make sure you are in the main directory of "istio-tutorial"

[source,bash]
----
istioctl create -f istiofiles/destination-rule-recommendation-v1-v2.yml -n $TUTORIAL_PROJECT
istioctl create -f istiofiles/virtual-service-recommendation-v1-mirror-v2.yml -n $TUTORIAL_PROJECT

curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
----

Check the logs of recommendation-v2

[source,bash]
----
oc logs -f dc/recommendation-v2 -c recommendation-v2
----

Clean up

[source,bash]
----
istioctl delete -f istiofiles/destination-rule-recommendation-v1-v2.yml -n $TUTORIAL_PROJECT
istioctl delete -f istiofiles/virtual-service-recommendation-v1-mirror-v2.yml -n $TUTORIAL_PROJECT
----

=== Load Balancer

By default, you will see "round-robin" style load-balancing, but you can change it up, with the RANDOM option being fairly visible to the naked eye.

Add another v2 pod to the mix

[source,bash]
----
oc scale dc/recommendation-v2 --replicas=2 -n $TUTORIAL_PROJECT
----

Wait a bit (oc get pods -w to watch)
and curl the customer endpoint many times

[source,bash]
----
curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
----

Add a 3rd v2 pod to the mix

[source,bash]
----
$ oc scale dc/recommendation-v2 --replicas=3 -n $TUTORIAL_PROJECT
$ oc get pods -w -n $TUTORIAL_PROJECT

NAME                                  READY     STATUS    RESTARTS   AGE
customer-1755156816-cjd2z             2/2       Running   0          1h
preference-3336288630-2cc6f          2/2       Running   0          1h
recommendation-v1-3719512284-bn42p   2/2       Running   0          59m
recommendation-v2-2815683430-97nnf   2/2       Running   0          43m
recommendation-v2-2815683430-d49n6   2/2       Running   0          51m
recommendation-v2-2815683430-tptf2   2/2       Running   0          33m
----

Wait for those 2/2 (two containers in each pod) and then poll the customer endpoint

[source,bash]
----
#!/bin/bash
while true
do curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
sleep .5
done
----

The results should follow a fairly normal round-robin distribution pattern

[source,bash]
----
customer => preference => recommendation v1 from '99634814-d2z2t': 1145
customer => preference => recommendation v2 from '2819441432-525lh': 1
customer => preference => recommendation v2 from '2819441432-rg45q': 2
customer => preference => recommendation v2 from '2819441432-bs5ck': 181
customer => preference => recommendation v1 from '99634814-d2z2t': 1146
customer => preference => recommendation v2 from '2819441432-rg45q': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 4
customer => preference => recommendation v2 from '2819441432-bs5ck': 182
----

Now, add the Random LB DestinationPolicy

[source,bash]
----
istioctl create -f istiofiles/destination-rule-recommendation_lb_policy_app.yml -n $TUTORIAL_PROJECT
----

And you should see a different pattern of which pod is being selected

[source,bash]
----
customer => preference => recommendation v2 from '2819441432-rg45q': 10
customer => preference => recommendation v2 from '2819441432-525lh': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 11
customer => preference => recommendation v1 from '99634814-d2z2t': 1153
customer => preference => recommendation v1 from '99634814-d2z2t': 1154
customer => preference => recommendation v1 from '99634814-d2z2t': 1155
customer => preference => recommendation v2 from '2819441432-rg45q': 12
customer => preference => recommendation v2 from '2819441432-525lh': 4
customer => preference => recommendation v2 from '2819441432-525lh': 5
customer => preference => recommendation v2 from '2819441432-rg45q': 13
customer => preference => recommendation v2 from '2819441432-rg45q': 14
----

Clean up

[source,bash]
----
istioctl delete -f istiofiles/destination-rule-recommendation_lb_policy_app.yml -n $TUTORIAL_PROJECT

oc scale deployment recommendation-v2 --replicas=1 -n $TUTORIAL_PROJECT
----
