== Fault Injection

Apply some chaos engineering by throwing in some HTTP errors or network delays. Understanding failure scenarios is a critical aspect of microservices architecture (aka distributed computing)

=== HTTP Error 503

By default, recommendation v1 and v2 are being randomly load-balanced as that is the default behavior in Kubernetes/OpenShift

[source,bash]
----
$ oc get pods -l app=recommendation -n $TUTORIAL_PROJECT

NAME                                  READY     STATUS    RESTARTS   AGE
recommendation-v1-3719512284-7mlzw   2/2       Running   6          18h
recommendation-v2-2815683430-vn77w   2/2       Running   0          3h
----

You can inject 503's, for approximately 50% of the requests

[source,bash]
----
istioctl create -f istiofiles/destination-rule-recommendation.yml -n $TUTORIAL_PROJECT
istioctl create -f istiofiles/virtual-service-recommendation-503.yml -n $TUTORIAL_PROJECT

curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
customer => preference => recommendation v1 from '99634814-sf4cl': 88
curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
customer => 503 preference => 503 fault filter abort
curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
customer => preference => recommendation v2 from '2819441432-qsp25': 51
----

Clean up

[source,bash]
----
istioctl delete -f istiofiles/virtual-service-recommendation-503.yml -n $TUTORIAL_PROJECT
----

=== Delay

The most insidious of possible distributed computing faults is not a "down" service but a service that is responding slowly, potentially causing a cascading failure in your network of services.

[source,bash]
----
istioctl create -f istiofiles/virtual-service-recommendation-delay.yml -n $TUTORIAL_PROJECT
----

And hit the customer endpoint

[source,bash]
----
#!/bin/bash
while true
do
time curl `oc get routes customer -o jsonpath --template '{.spec.host}'`
sleep .5
done
----

You will notice many requests to the customer endpoint now have a delay.
If you are monitoring the logs for recommendation v1 and v2, you will also see the delay happens BEFORE the recommendation service is actually called

[source,bash]
----
oc logs dc/recommendation -n $TUTORIAL_PROJECT
----

Clean up

[source]
----
istioctl delete -f istiofiles/destination-rule-recommendation.yml -n $TUTORIAL_PROJECT
istioctl delete -f istiofiles/virtual-service-recommendation-delay.yml -n $TUTORIAL_PROJECT
----

=== Timeout

Wait only N seconds before giving up and failing. At this point, no other virtual service nor destination rule (in `tutorial` namespace) should be in effect. To check it run `istioctl get virtualservice` `istioctl get destinationrule` and if so `istioctl delete virtualservice virtualservicename -n $TUTORIAL_PROJECT` and `istioctl delete destinationrule destinationrulename -n $TUTORIAL_PROJECT`

First, introduce some wait time in `recommendation v2` by uncommenting the line that calls the `timeout()` method. Update `RecommendationVerticle.java` making it a slow performer with a 3 second delay.

[source,java]
----
    @Override
    public void start() throws Exception {
        Router router = Router.router(vertx);
        router.get("/").handler(this::logging);
        router.get("/").handler(this::timeout);
        router.get("/").handler(this::getRecommendations);
        router.get("/misbehave").handler(this::misbehave);
        router.get("/behave").handler(this::behave);

        HealthCheckHandler hc = HealthCheckHandler.create(vertx);
        hc.register("dummy-health-check", future -> future.complete(Status.OK()));
        router.get("/health").handler(hc);

        vertx.createHttpServer().requestHandler(router::accept).listen(8080);
    }
----

Rebuild and redeploy

[source, bash]
----
oc start-build recommendation-v2 --from-dir=. --follow
----


Hit the customer endpoint a few times, to see the load-balancing between v1 and v2 but with v2 taking a bit of time to respond

[source,bash]
----
#!/bin/bash
while true
do
time curl customer-tutorial.$(minishift ip).nip.io
sleep .5
done
----

Then add the timeout rule

[source,bash]
----
istioctl create -f istiofiles/virtual-service-recommendation-timeout.yml -n $TUTORIAL_PROJECT
----

You will see it return v1 OR "upstream request timeout" after waiting about 1 second

[source,bash]
----
#!/bin/bash
while true
do
time curl customer-tutorial.$(minishift ip).nip.io
sleep .5
done

customer => 503 preference => 504 upstream request timeout
curl customer-tutorial.$(minishift ip).nip.io  0.01s user 0.00s system 0% cpu 1.035 total
customer => preference => recommendation v1 from '2039379827-h58vw': 210
curl customer-tutorial.$(minishift ip).nip.io  0.01s user 0.00s system 36% cpu 0.025 total
customer => 503 preference => 504 upstream request timeout
curl customer-tutorial.$(minishift ip).nip.io  0.01s user 0.00s system 0% cpu 1.034 total
----

Clean up, delete the timeout rule

[source,bash]
----
istioctl delete -f istiofiles/virtual-service-recommendation-timeout.yml -n $TUTORIAL_PROJECT
----
